name: .NET CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'      # optional: allow release/tag builds
  pull_request:
    branches: [ main, develop ]

# optional: cancel older runs for the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore
        run: dotnet restore FastChartsSolution.sln

      - name: Build
        run: dotnet build FastChartsSolution.sln --configuration Release --no-restore /p:EnableWindowsTargeting=true /p:TreatWarningsAsErrors=false

      - name: Test
        run: dotnet test FastChartsSolution.sln --configuration Release /p:EnableWindowsTargeting=true --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/**/coverage.cobertura.xml
